/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PHAN1;

/**
 *
 * @author NAM PC
 */
public class Bai3 extends javax.swing.JFrame {

    /**
     * Creates new form Bai3
     */
    public Bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnsv = new javax.swing.JButton();
        btnnhapdiem = new javax.swing.JButton();
        btnbangdiem = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        munidoimk = new javax.swing.JMenuItem();
        mnuidangxuat = new javax.swing.JMenuItem();
        mnuiketthuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuiqlsv = new javax.swing.JMenuItem();
        mnuiqldiem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuigioithieu = new javax.swing.JMenuItem();
        mnuihdsd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnsv.setText("Sinh Viên");
        jToolBar1.add(btnsv);

        btnnhapdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnnhapdiem.setText("Nhập Điểm ");
        jToolBar1.add(btnnhapdiem);

        btnbangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Notes.png"))); // NOI18N
        btnbangdiem.setText("Bảng Điểm");
        jToolBar1.add(btnbangdiem);

        btnketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnketthuc.setText("Kết Thúc");
        jToolBar1.add(btnketthuc);

        jMenu1.setText("Hệ Thống");

        munidoimk.setText("Đổi mật khẩu");
        jMenu1.add(munidoimk);

        mnuidangxuat.setText("Đăng xuất");
        jMenu1.add(mnuidangxuat);

        mnuiketthuc.setText("Kết thúc");
        jMenu1.add(mnuiketthuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        mnuiqlsv.setText("Quản lý sinh viên");
        jMenu2.add(mnuiqlsv);

        mnuiqldiem.setText("Quản lý điểm ");
        mnuiqldiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiqldiemActionPerformed(evt);
            }
        });
        jMenu2.add(mnuiqldiem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ Giúp");

        mnuigioithieu.setText("Giới thiệu");
        jMenu3.add(mnuigioithieu);

        mnuihdsd.setText("HD sử dụng");
        jMenu3.add(mnuihdsd);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiqldiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiqldiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuiqldiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbangdiem;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JButton btnnhapdiem;
    private javax.swing.JButton btnsv;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuidangxuat;
    private javax.swing.JMenuItem mnuigioithieu;
    private javax.swing.JMenuItem mnuihdsd;
    private javax.swing.JMenuItem mnuiketthuc;
    private javax.swing.JMenuItem mnuiqldiem;
    private javax.swing.JMenuItem mnuiqlsv;
    private javax.swing.JMenuItem munidoimk;
    // End of variables declaration//GEN-END:variables
}
