/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.lab6thread;

import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author adm1n
 */
public class ThreadBai2 extends javax.swing.JFrame {

    /**
     * Creates new form ThreadBai2
     */
    public ThreadBai2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txthangtram = new javax.swing.JTextField();
        txthangchuc = new javax.swing.JTextField();
        txthangdonvi = new javax.swing.JTextField();
        btnhangtram = new javax.swing.JButton();
        btnhangchuc = new javax.swing.JButton();
        btnhangdonvi = new javax.swing.JButton();
        btnstop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnhangtram.setText("Start");
        btnhangtram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangtramActionPerformed(evt);
            }
        });

        btnhangchuc.setText("Start");
        btnhangchuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangchucActionPerformed(evt);
            }
        });

        btnhangdonvi.setText("Start");
        btnhangdonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangdonviActionPerformed(evt);
            }
        });

        btnstop.setText("Stop");
        btnstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhangtram)
                    .addComponent(txthangtram, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnstop)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhangchuc)
                            .addComponent(txthangchuc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhangdonvi)
                            .addComponent(txthangdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthangtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangchuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhangtram)
                    .addComponent(btnhangchuc)
                    .addComponent(btnhangdonvi))
                .addGap(39, 39, 39)
                .addComponent(btnstop)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  ThreadXoSo hangtram;
  ThreadXoSo hangchuc;
  ThreadXoSo hangdonvi;
  
  
    private void btnhangtramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangtramActionPerformed
   hangtram = new ThreadXoSo(txthangtram);
   hangtram.start();
   btnhangtram.setEnabled(false);
        
  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhangtramActionPerformed

    private void btnstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstopActionPerformed
        // TODO add your handling code here
        
        hangtram.stop();
        btnhangtram.setEnabled(true);
        
        
        hangchuc.stop();
        btnhangchuc.setEnabled(true);
       
        hangdonvi.stop();
        btnhangdonvi.setEnabled(true);
    }//GEN-LAST:event_btnstopActionPerformed

    private void btnhangchucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangchucActionPerformed
        // TODO add your handling code here:
        
   hangchuc= new ThreadXoSo(txthangchuc);
   hangchuc.start();
   btnhangchuc.setEnabled(false);
        
    }//GEN-LAST:event_btnhangchucActionPerformed

    private void btnhangdonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangdonviActionPerformed
        // TODO add your handling code here:
        hangdonvi= new ThreadXoSo(txthangdonvi);
        hangdonvi.start();
        btnhangdonvi.setEnabled(false);
    }//GEN-LAST:event_btnhangdonviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreadBai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhangchuc;
    private javax.swing.JButton btnhangdonvi;
    private javax.swing.JButton btnhangtram;
    private javax.swing.JButton btnstop;
    private javax.swing.JTextField txthangchuc;
    private javax.swing.JTextField txthangdonvi;
    private javax.swing.JTextField txthangtram;
    // End of variables declaration//GEN-END:variables
}
