/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PHAN2;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author NAM PC
 */
public class ChangePassword extends javax.swing.JFrame {

    List<User> list = new ArrayList<>();

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        setLocationRelativeTo(null);
        initData();
    }

    public boolean check_null() {
        if (txtusername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "hãy nhập username");
            txtusername.setBackground(Color.red);
            txtusername.requestFocus();
            return false;
        }
        if (pwdcurrent.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "hãy nhập password");
            pwdcurrent.setBackground(Color.red);
            pwdcurrent.requestFocus();
            return false;
        }
        if (pwdnewpass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "hãy nhập password mới");
            pwdnewpass.setBackground(Color.red);
            pwdnewpass.requestFocus();
            return false;
        }
        if (txtconfirmpass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "hãy nhập xác nhận mất khẩu");
            txtconfirmpass.setBackground(Color.red);
            txtconfirmpass.requestFocus();
            return false;
        }

        txtusername.setBackground(Color.white);
        pwdcurrent.setBackground(Color.white);
        pwdnewpass.setBackground(Color.white);
        txtconfirmpass.setBackground(Color.white);
        return true;
    }

    public boolean check_null2() {
        if (txtusername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "hãy nhập username");
            txtusername.setBackground(Color.red);
            txtusername.requestFocus();
            return false;
        }
        if (pwdcurrent.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "hãy nhập password");
            pwdcurrent.setBackground(Color.red);
            pwdcurrent.requestFocus();
            return false;
        }
        txtusername.setBackground(Color.white);
        pwdcurrent.setBackground(Color.white);
        return true;
    }

    public void initData() {
        User user = new User();
//        User user2 = new User();

        user.setUserName("fpt");
        user.setPwdPassWord("123");

//        user2.setUserName("abc");
//        user2.setPwdPassWord("456");
        list.add(user);
//        list.add(user2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtconfirmpass = new javax.swing.JTextField();
        pwdcurrent = new javax.swing.JPasswordField();
        pwdnewpass = new javax.swing.JPasswordField();
        btncancel = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        btnsignin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("CHANGE PASSWORD");

        jLabel2.setText("Username");

        jLabel3.setText("Current Password");

        jLabel4.setText("New Password");

        jLabel5.setText("Confirm Password");

        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Stop.png"))); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        btnsignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Accept.png"))); // NOI18N
        btnsignin.setText("Sign In");
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnok)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pwdnewpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtusername, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncancel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(txtconfirmpass, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(pwdcurrent))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnsignin)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnok))
                .addGap(18, 18, 18)
                .addComponent(btnsignin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        if (check_null()) {
            for (User user : list) {
                if (!txtusername.getText().equals(user.getUserName())) {
                    JOptionPane.showMessageDialog(this, "user không tồn tại ! hãy nhập lại");
                    txtusername.requestFocus();
                } else {
                    if (pwdcurrent.getText().equals(pwdnewpass.getText())) {
                        JOptionPane.showMessageDialog(this, "password cũ và mới giống nhau");
                        pwdcurrent.setBackground(Color.red);
                        pwdnewpass.setBackground(Color.red);
                        pwdnewpass.requestFocus();
                    } else {
                        pwdcurrent.setBackground(Color.white);
                        pwdnewpass.setBackground(Color.white);
                        if (pwdnewpass.getText().equals(txtconfirmpass.getText())) {
                            for (User user1 : list) {
                                user1.setPwdPassWord(pwdnewpass.getText());
                            }
                            JOptionPane.showMessageDialog(this, "thay đổi password thành công");
                        } else {
                            JOptionPane.showMessageDialog(this, "thay đổi password không thành công");
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_btnokActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(this, "bạn có muốn thoát không", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choose == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        // TODO add your handling code here:
        if (check_null2()) {
            for (User user : list) {
                if (txtusername.getText().equalsIgnoreCase(user.getUserName()) && pwdcurrent.getText().equalsIgnoreCase(user.getPwdPassWord())) {
                    JOptionPane.showMessageDialog(this, "đăng nhập thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "đăng nhập thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnsigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pwdcurrent;
    private javax.swing.JPasswordField pwdnewpass;
    private javax.swing.JTextField txtconfirmpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
