/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.lab23;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adm1n
 */
public class NhanVienGui extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienGui
     */
 DefaultTableModel model;
    public void loadtieude()
{
   model = new DefaultTableModel();
   model.addColumn("Mã");
   model.addColumn("ten Anh Tú");
   model.addColumn("giới tình");
   model.addColumn("vai trò");
   tbldanhsachnhanvien.setModel(model);
  
    
}
    ArrayList<NhanVien> arrnv = new ArrayList<>();
   public void LoadDataMautoArrayList()
   {
       arrnv.add(new NhanVien("nv01", "Chí", true, 0));
       arrnv.add(new NhanVien("nv02", "Công", true, 1));
       arrnv.add(new NhanVien("nv01", "Vô", false, 0));
       arrnv.add(new NhanVien("nv01", "Tư", true, 2));
       
      /* NhanVien nv = new NhanVien();
       nv.setManv("nv01");
       nv.setTennv("chí");
       nv.setGioitinh(true);
       nv.setVaitro(0);
       arrnv.add(nv);
       */
                 
       
   }
   public void LoadDataArrayListToTable()
   {
       DefaultTableModel model = (DefaultTableModel) tbldanhsachnhanvien.getModel();
       model.setRowCount(0);
       String gt;
       String vaitro;
       for(NhanVien nv : arrnv)
       {
           if (nv.getGioitinh()==true)
               gt="Nam";
           else
               gt="nữ";
           
           if(nv.getVaitro()==0)
               vaitro="nhân viên";
           else if (nv.getVaitro()==1)
               vaitro="quản trị";
           else
               vaitro="giám đốc";
           
           model.addRow(new Object[]{nv.getManv(),nv.getTennv(),gt,vaitro });
       }
       
      /*
      for(int i=0; i<arrnv.size(); i++)
      {
          Vector v = new Vector();
          v.add(arrnv.get(i).getManv());
          v.add(arrnv.get(i).getTennv());
          v.add(arrnv.get(i).getGioitinh());
          v.add(arrnv.get(i).getVaitro());
          model.addRow(v);
      }
      */
   }
    public NhanVienGui() {
        initComponents();
        loadtieude();
        LoadDataMautoArrayList();
        LoadDataArrayListToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupgt = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttennv = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnthemmoi = new javax.swing.JButton();
        cbovaitro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbldanhsachnhanvien = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnghifiledangbuffer = new javax.swing.JButton();
        btndocfiledangbuffer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setText("Tên Nhân Viên");

        btngroupgt.add(rdonam);
        rdonam.setText("Nam");

        btngroupgt.add(rdonu);
        rdonu.setText("Nữ");

        jLabel3.setText("Giới Tính");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdonu)
                    .addComponent(rdonam))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addComponent(rdonam)
                .addGap(18, 18, 18)
                .addComponent(rdonu))
        );

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnthemmoi.setText("Thêm Mới");
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });

        cbovaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Quản Trị", "Giám Đốc" }));

        jLabel4.setText("Vai trò");

        tbldanhsachnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Gioi TInh", "Vai Tro"
            }
        ));
        tbldanhsachnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldanhsachnhanvienMouseClicked(evt);
            }
        });
        tbldanhsachnhanvien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbldanhsachnhanvienKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbldanhsachnhanvien);

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnghifiledangbuffer.setText("ghifile dang buffer");
        btnghifiledangbuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghifiledangbufferActionPerformed(evt);
            }
        });

        btndocfiledangbuffer.setText("docfile dang buffer");
        btndocfiledangbuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocfiledangbufferActionPerformed(evt);
            }
        });

        jButton3.setText("ghiflile dang object(ma hoa)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("docfile dang object");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnghifiledangbuffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndocfiledangbuffer, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addComponent(cbovaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(91, 91, 91)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtmanv)
                                        .addComponent(txttennv, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                    .addGap(74, 74, 74)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnthem)
                                        .addComponent(btnxoa)
                                        .addComponent(btnsua)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 244, Short.MAX_VALUE)
                                            .addComponent(btnthemmoi))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1)
                                            .addGap(0, 0, Short.MAX_VALUE))))))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnthem))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnxoa)))
                        .addGap(18, 18, 18)
                        .addComponent(btnsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnthemmoi)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton1)
                                            .addComponent(jButton2))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbovaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnghifiledangbuffer)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(btndocfiledangbuffer))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
txtmanv.setText("");
txttennv.setText("");
rdonam.setSelected(true);

    }//GEN-LAST:event_btnthemmoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed

        // TODO add your handling code here:

        int them=1;
        for(NhanVien nv : arrnv)
       {
           if(nv.getManv().equalsIgnoreCase(txtmanv.getText()))
               them=0;
       }
        if(them==0)
            JOptionPane.showMessageDialog(this, "Trùng Mã rồi");
        else
        {
        NhanVien nv = new NhanVien();
        nv.setManv(txtmanv.getText());
        nv.setTennv(txttennv.getText());
         boolean gt=true;
        if (rdonam.isSelected())
            gt=true;
        else
            gt=false;
        nv.setGioitinh(gt);
        nv.setVaitro(cbovaitro.getSelectedIndex());
               
        arrnv.add(nv);
        
        LoadDataArrayListToTable();
        JOptionPane.showMessageDialog(this, "Thêm Thành CÔng");
        }
    }//GEN-LAST:event_btnthemActionPerformed
 int vitri=-1; //chưa được chọn
 public void filltocontrol(int vitri)
 {
     txtmanv.setText(arrnv.get(vitri).getManv());
        txttennv.setText(arrnv.get(vitri).getTennv());
        
       if(arrnv.get(vitri).getGioitinh()==true)
            rdonam.setSelected(true);
       else
           rdonu.setSelected(true);
       
        cbovaitro.setSelectedIndex(arrnv.get(vitri).getVaitro());
 }
 
    private void tbldanhsachnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldanhsachnhanvienMouseClicked
        // TODO add your handling code here:
        vitri=tbldanhsachnhanvien.getSelectedRow();
        filltocontrol(vitri);
        
        
    }//GEN-LAST:event_tbldanhsachnhanvienMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
       NhanVien nv = new NhanVien();
       boolean gt=true;
       nv.setManv(txtmanv.getText());
       nv.setTennv(txttennv.getText());
      if(rdonam.isSelected())
          gt=true;
      else
          gt=false;
      
       nv.setGioitinh(gt);
       nv.setVaitro(cbovaitro.getSelectedIndex());
        arrnv.set(vitri, nv);
        LoadDataArrayListToTable();
        
        
    }//GEN-LAST:event_btnsuaActionPerformed

    private void tbldanhsachnhanvienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbldanhsachnhanvienKeyPressed
        // TODO add your handling code here:
        vitri=tbldanhsachnhanvien.getSelectedRow();
        filltocontrol(vitri);
    }//GEN-LAST:event_tbldanhsachnhanvienKeyPressed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if(vitri==-1)
            JOptionPane.showMessageDialog(this, "Bạn Chưa chọn NV để xóa");
        else
        {  
        arrnv.remove(vitri);
        LoadDataArrayListToTable();
         JOptionPane.showMessageDialog(this, "Success");
        } 
        
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

      
     try
     {        
//if(vitri<arrnv.size())
         {vitri=vitri+1;
            filltocontrol(vitri);
         tbldanhsachnhanvien.setRowSelectionInterval(vitri, vitri);
        
         }
     }
     catch(Exception ex)
     {
         JOptionPane.showMessageDialog(this, "ddang o phan tu cuoi");
     }
      
      
        
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(vitri>0)
        {vitri=vitri - 1;
            filltocontrol(vitri);
        tbldanhsachnhanvien.setRowSelectionInterval(vitri, vitri);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

   
    public boolean luudangbuffer(ArrayList<NhanVien> listnv, String duongdan )
    {
        try
        {
      FileOutputStream fos = new FileOutputStream(duongdan);
      OutputStreamWriter osw= new OutputStreamWriter(fos,"UTF-8");
      BufferedWriter bw=new BufferedWriter(osw);
         for(NhanVien nv: listnv)   
         {
             String luudong=nv.getManv() + "-" + nv.getTennv() + "-" + nv.getGioitinh() + "-" + nv.getVaitro();
             bw.write(luudong);
             bw.newLine();
                      
         }
         bw.close();
         osw.close();
         fos.close();
      
        return true;      
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi Hệ Thống");
        }
               
      
        
        
        
        return false;
        
    }
    
    private void btnghifiledangbufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghifiledangbufferActionPerformed
        // TODO add your handling code here:
        
   
        if(luudangbuffer(arrnv,"d:\\anhtubuffer2.txt")==true)
                {
                    JOptionPane.showMessageDialog(this, "Lưu Thanh Cong");
                }
        
        
    }//GEN-LAST:event_btnghifiledangbufferActionPerformed

    public void docfiledangbuffer(String duongdan)
    {
        arrnv.clear();
        try
        {
            FileInputStream fin= new FileInputStream(duongdan);
            InputStreamReader in = new InputStreamReader(fin, "UTF-8");
            BufferedReader bfr= new BufferedReader(in);
            String docdong=bfr.readLine();
            while(docdong!=null)
            {
                NhanVien listdoc= new NhanVien();
            
                String arr[]=docdong.split(";");
                if(arr.length==4)
                {listdoc.setManv(arr[0]);
                listdoc.setTennv(arr[1]);
                listdoc.setGioitinh(Boolean.parseBoolean(arr[3]));
                listdoc.setVaitro(Integer.parseInt(arr[3]));
                arrnv.add(listdoc);
                }
                
             docdong=bfr.readLine();
            
            }
         
        bfr.close();
        in.close();
        fin.close();
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Lỗi Hệ Thống");
        }
        
    }
    
    public void docfiledangbuffer1(String duongdan)
    {
        arrnv.clear();
        try
        {
            FileInputStream fin = new FileInputStream(duongdan);
            InputStreamReader in = new InputStreamReader(fin,"UTF-8");
            BufferedReader bfr = new BufferedReader(in);
            String docdong=bfr.readLine();
            while(docdong!=null)
            {
                NhanVien listdoc = new NhanVien();
                String arr[]=docdong.split(";");
                if(arr.length==4)
                {
                    listdoc.setManv(arr[0]);
                    listdoc.setTennv(arr[1]);
                    listdoc.setGioitinh(Boolean.parseBoolean(arr[2]));
                    listdoc.setVaitro(Integer.parseInt(arr[3]));
                    arrnv.add(listdoc);
                } 
                
                docdong=bfr.readLine();
                
            }
            bfr.close();
            in.close();
            fin.close();
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }        
    }
    
    private void btndocfiledangbufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocfiledangbufferActionPerformed
        // TODO add your handling code here:
        
        docfiledangbuffer2("d:\\anhtubuffer2.txt");
       LoadDataArrayListToTable();
       JOptionPane.showMessageDialog(this, "doc file thanh cong");
        
    }//GEN-LAST:event_btndocfiledangbufferActionPerformed

    public boolean luudangobject2(ArrayList<NhanVien> listnv, String duongdan)
    {
        try
        {
            FileOutputStream fo= new FileOutputStream(duongdan);
            ObjectOutputStream objo= new ObjectOutputStream(fo);
            objo.writeObject(listnv);
            objo.close();
            fo.close();
                    return true;
        }     
       catch(Exception ex)
       {
        JOptionPane.showMessageDialog(this, "Lỗi Hệ Thống");     
       }
              
        return false;
        
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(luudangobject2(arrnv,"d:\\anhtuobject.txt")==true)
             JOptionPane.showMessageDialog(this, "Luu thành công");          
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void docfileobject2(String duongdan)
    {
        try
        {
        
            FileInputStream fin = new FileInputStream(duongdan);
            ObjectInputStream objin = new ObjectInputStream(fin);
          Object doc =objin.readObject();
          arrnv=(ArrayList<NhanVien>) doc;
          
          objin.close();
          fin.close();
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        docfileobject2("d:\\anhtuobject.txt");
        LoadDataArrayListToTable();
        JOptionPane.showMessageDialog(this, "đọc thành công");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public boolean luufiledangbuffer(ArrayList<NhanVien> listnv, String duongdan)
    {
        try
        {
            
            FileOutputStream fos = new FileOutputStream(duongdan);
            OutputStreamWriter osw = new OutputStreamWriter(fos,"UTF-8");
            BufferedWriter bw= new BufferedWriter(osw);
            for(NhanVien nv : listnv)
            {
                String luudong=nv.getManv() + "-" + nv.getTennv()+ "-" + nv.getGioitinh() + "-" + nv.getVaitro();
                bw.write(luudong);
                bw.newLine();
                
            }
            bw.close();
            osw.close();
            fos.close();
               
                 
            
            return true;
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Loi");
            
            
        }
        
    return false;    
    }
    
    
    public void docfiledangbuffer2(String duongdan)
    {
       arrnv.clear();
       try
       {
           FileInputStream fin = new  FileInputStream(duongdan);
           InputStreamReader in = new InputStreamReader(fin,"UTF-8");  
           BufferedReader bfr=new BufferedReader(in);
           
            String docdong=bfr.readLine();
           while(docdong!=null)
           {
               NhanVien listdoc= new NhanVien();
               String arr[]=docdong.split("-");
               if(arr.length==4)
               {
               listdoc.setManv(arr[0]);
               listdoc.setTennv(arr[1]);
               listdoc.setGioitinh(Boolean.parseBoolean(arr[2]));
               listdoc.setVaitro(Integer.parseInt(arr[3]));
               arrnv.add(listdoc);
               }
               
               docdong=bfr.readLine();
               
           }
           
           bfr.close();
           in.close();
           fin.close();
            
       }
       
      
       catch(Exception ex)
       {
       ex.printStackTrace();
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndocfiledangbuffer;
    private javax.swing.JButton btnghifiledangbuffer;
    private javax.swing.ButtonGroup btngroupgt;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbovaitro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tbldanhsachnhanvien;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txttennv;
    // End of variables declaration//GEN-END:variables
}
