/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoassigment;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adm1n
 */
public class NhanVienGui extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form NhanVienGui
     */
    Thread dongho;

    public void LoadDongHo() {
        dongho = new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Date d = new Date();
                        SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss aa dd/MM/YYYY");
                        String time = f.format(d);
                        lbldongho.setText(time);
                        Thread.sleep(1000);

                    } catch (Exception ex) {
                        break;
                    }

                }
            }

        };
        dongho.start();

    }

    public NhanVienGui() {
        initComponents();
        LoadDongHo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txttuoi = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtluong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldanhsach = new javax.swing.JTable();
        btnlui = new javax.swing.JButton();
        btntoi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnthemmoi = new javax.swing.JButton();
        txttim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblanh = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lbldongho = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setText("Ho va ten");

        jLabel3.setText("Tuoi");

        jLabel4.setText("EMail");

        tbldanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ Tên", "Tuổi", "Email", "Lương"
            }
        ));
        tbldanhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldanhsachMouseClicked(evt);
            }
        });
        tbldanhsach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbldanhsachKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbldanhsach);

        btnlui.setText("<<");
        btnlui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluiActionPerformed(evt);
            }
        });

        btntoi.setText(">>");
        btntoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoiActionPerformed(evt);
            }
        });

        jButton5.setText("Mở File");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jButton9.setText("Lưu File");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Thoat");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnthemmoi.setText("Thêm Mới");
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });

        txttim.setText("Tìm");
        txttim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Quản Lý Nhân Viên");

        jButton2.setText("Sắp xếp theo Họ Tên");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoassigment/Anh/anh1.JPG"))); // NOI18N
        lblanh.setText("jLabel7");

        jButton3.setText("Chọn Ảnh");
        jButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton3StateChanged(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbldongho.setText("jLabel7");

        jLabel6.setText("Lương");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtluong, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(txtemail)
                                    .addComponent(txttuoi)
                                    .addComponent(txtmanv)
                                    .addComponent(txthoten))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblanh, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton5)
                        .addGap(71, 71, 71)
                        .addComponent(jButton10)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(btnlui)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btntoi))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton9)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnthemmoi)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnthem)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnxoa)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnsua)
                                    .addGap(38, 38, 38)
                                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlui)
                            .addComponent(btntoi))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldongho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblanh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemmoi)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnsua)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<NhanVien> arrnhanvien = new ArrayList<>();
    String duongdananh = "D:\\FPT\\JAVA2\\java2spring20213\\src\\demoassigment\\Anh\\anh1.JPG";

    public void fillDaTaToArrayList() {
        NhanVien nv = new NhanVien();
        nv.setManv(txtmanv.getText());
        nv.setHoten(txthoten.getText());
        nv.setEmail(txtemail.getText());
        nv.setTuoi(Integer.parseInt(txttuoi.getText()));
        nv.setLuong(Double.parseDouble(txtluong.getText()));
        nv.setAnh(duongdananh);

        arrnhanvien.add(nv);
    }

    public void fillArrayListToTable() {

        DefaultTableModel model = (DefaultTableModel) tbldanhsach.getModel();
        model.setRowCount(0);
        /* for(NhanVien nv : arrnhanvien)
        {
            model.addRow(new Object[]{nv.getManv(),nv.getHoten(),nv.getTuoi(),nv.getEmail(),nv.getLuong() });
      
        }
         */
        for (NhanVien nv : arrnhanvien) {
            Vector vec = new Vector();
            vec.add(nv.getManv());
            vec.add(nv.getHoten());
            vec.add(nv.getTuoi());
            vec.add(nv.getEmail());
            vec.add(nv.getLuong());
            vec.add(nv.getAnh());
            model.addRow(vec);
        }

    }


    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
        txtmanv.setText("");
        txtemail.setText("");
        txthoten.setText("");
        txtluong.setText("");
        txttuoi.setText("");


    }//GEN-LAST:event_btnthemmoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:

        fillDaTaToArrayList();
        fillArrayListToTable();
        JOptionPane.showMessageDialog(this, "Thêm Thành Công");


    }//GEN-LAST:event_btnthemActionPerformed
    int vitri = -1;

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void filltocontroll(int vitri) {
        txtmanv.setText(arrnhanvien.get(vitri).getManv());
        txthoten.setText(arrnhanvien.get(vitri).getHoten());
        txtemail.setText(arrnhanvien.get(vitri).getEmail());
        txttuoi.setText(String.valueOf(arrnhanvien.get(vitri).getTuoi()));
        txtluong.setText(String.valueOf(arrnhanvien.get(vitri).getLuong()));
        lblanh.setIcon(ResizeImage(String.valueOf(arrnhanvien.get(vitri).getAnh())));

    }
    private void tbldanhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldanhsachMouseClicked
        // TODO add your handling code here:

        vitri = tbldanhsach.getSelectedRow();

        System.out.println(vitri);
        if (co == 0) {
            filltocontroll(vitri);

        } else {
            filltocontroll(l2.get(vitri).getVitri());
            System.out.println(l2.get(vitri).getVitri());
        }


    }//GEN-LAST:event_tbldanhsachMouseClicked

    private void btntoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoiActionPerformed
        // TODO add your handling code here:
        if (vitri < arrnhanvien.size()) {
            vitri = vitri + 1;
            filltocontroll(vitri);
            tbldanhsach.setRowSelectionInterval(vitri, vitri);
        }
    }//GEN-LAST:event_btntoiActionPerformed

    private void btnluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluiActionPerformed
        // TODO add your handling code here:
        if (vitri > 0) {
            vitri = vitri - 1;
            filltocontroll(vitri);
            tbldanhsach.setRowSelectionInterval(vitri, vitri);
        }
    }//GEN-LAST:event_btnluiActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (co == 0) {
            if (vitri != -1) {
                arrnhanvien.remove(vitri);
                JOptionPane.showMessageDialog(this, "Xóa Thành công");
                fillArrayListToTable();
            } else {
                JOptionPane.showMessageDialog(this, "bạn phải chọn vào table nv muốn xóa");
            }
        } else {
            arrnhanvien.remove(l2.get(vitri).getVitri());
            fillArrayListToTable();
            co = 0;
            JOptionPane.showMessageDialog(this, "Xóa Thành công");

        }

        // tuong tự cho nut update.

    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (co == 0) {
            if (vitri != -1) {
                NhanVien nv = new NhanVien();
                nv.setManv(txtmanv.getText());
                nv.setHoten(txthoten.getText());
                nv.setLuong(Double.parseDouble(txtluong.getText()));
                nv.setTuoi(Integer.parseInt(txttuoi.getText()));
                nv.setEmail(txtemail.getText());

                nv.setAnh(duongdananh);
                arrnhanvien.set(vitri, nv);

                fillArrayListToTable();
                JOptionPane.showMessageDialog(this, "Đã sửa Thành Công");
            } else {
                JOptionPane.showMessageDialog(this, "Chọn Nhân Viên Cần Sửa");
            }
        } else //co==1
        {
            NhanVien nv = new NhanVien();
            nv.setManv(txtmanv.getText());
            nv.setHoten(txthoten.getText());
            nv.setLuong(Double.parseDouble(txtluong.getText()));
            nv.setTuoi(Integer.parseInt(txttuoi.getText()));
            nv.setEmail(txtemail.getText());
            nv.setAnh(duongdananh);
            arrnhanvien.set(l2.get(vitri).getVitri(), nv);

            fillArrayListToTable();
            co = 0;
            JOptionPane.showMessageDialog(this, "Đã sửa Thành Công");

        }


    }//GEN-LAST:event_btnsuaActionPerformed

    public static boolean luudang2object(ArrayList<NhanVien> sv, String duongdan) { // lớp Mô hình student phải kết thừa từ lớp Serializable nhé.
        try {
            FileOutputStream fo = new FileOutputStream(duongdan);// đường dẫn lưu
            ObjectOutputStream objo = new ObjectOutputStream(fo); // lưu luôn đối tượng object (file ảnh), 
            objo.writeObject(sv); // ghi xuống file
            objo.close(); // đóng file
            fo.close();

            return true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "lỗi file, đường dẫn lưu file");
            ex.printStackTrace();
            return false;

        }
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (luudang2object(arrnhanvien, "d:\\luudangobject1.txt") == true) {
            JOptionPane.showMessageDialog(null, "Lưu thành công");
        } else
            JOptionPane.showMessageDialog(null, "lỗi hệ thống");
    }//GEN-LAST:event_jButton9ActionPerformed

    public void docfileobject(String duongdan) // dọc file vào list
    {
        try {
            // ArrayList<Student> ldoc = new ArrayList<>();
            FileInputStream fin = new FileInputStream(duongdan);
            ObjectInputStream objin = new ObjectInputStream(fin);
            Object doc = objin.readObject();
            arrnhanvien = (ArrayList<NhanVien>) doc;
            objin.close();
            fin.close();
            JOptionPane.showMessageDialog(null, "đọc file thành công");

        } catch (Exception ex) {
            ex.printStackTrace();

        }

    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        docfileobject("d:\\luudangobject1.txt");
        fillArrayListToTable();

    }//GEN-LAST:event_jButton5ActionPerformed

    ArrayList<NhanVienTim> l2 = new ArrayList<>();

    public void tim() {
        l2.clear();
        for (int i = 0; i < arrnhanvien.size(); i++) {
            //if(l.get(i).getName().startsWith(txttim.getText())==true)
            if (arrnhanvien.get(i).getHoten().contains(txttim.getText()) == true) {

                int vitri = i;
                String ma = arrnhanvien.get(i).getManv();
                String hoten = arrnhanvien.get(i).getHoten();
                int tuoi = arrnhanvien.get(i).getTuoi();
                String email = arrnhanvien.get(i).getEmail();
                double luong = arrnhanvien.get(i).getLuong();
                String anh = arrnhanvien.get(i).getAnh();
                NhanVienTim nvtim = new NhanVienTim(i, ma, hoten, tuoi, email, luong, anh);

                l2.add(nvtim);
                //tìm l?nh ch?n dòng.

            }

        }

        ArrayListTimToTable();// d? l?i t? arraylisttìm ki?m lên table
    }

    public void ArrayListTimToTable() {
        DefaultTableModel model = (DefaultTableModel) tbldanhsach.getModel();
        model.setRowCount(0);
        for (int i = 0; i < l2.size(); i++) {
            String ma = l2.get(i).getManv();
            String hoten = l2.get(i).getHoten();
            int tuoi = l2.get(i).getTuoi();
            String email = l2.get(i).getEmail();
            double luong = l2.get(i).getLuong();

            Object[] row = new Object[]{ma, hoten, tuoi, email, luong};
            model.addRow(row);
        }
    }

    int co = 0;
    private void txttimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimKeyReleased
        tim();
        co = 1;
    }//GEN-LAST:event_txttimKeyReleased

    private void tbldanhsachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbldanhsachKeyReleased
        // TODO add your handling code here:
        vitri = tbldanhsach.getSelectedRow();

        System.out.println(vitri);
        if (co == 0) {
            filltocontroll(vitri);

        } else {
            filltocontroll(l2.get(vitri).getVitri());
            System.out.println(l2.get(vitri).getVitri());
        }

    }//GEN-LAST:event_tbldanhsachKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Comparator<NhanVien> sx = new Comparator<NhanVien>() {
            @Override
            public int compare(NhanVien o1, NhanVien o2) {
                return o1.getHoten().compareTo(o2.getHoten()); //To change body of generated methods, choose Tools | Templates.
            }
        }; // có dấu chấm phẩy.
        Collections.sort(arrnhanvien, sx);
        fillArrayListToTable();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "bạn muốn thoát không", "thoát", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            JFileChooser f = new JFileChooser("D:\\anh");
            f.setDialogTitle("Mở file");
            f.showOpenDialog(null);
            File ftenanh = f.getSelectedFile();
            duongdananh = ftenanh.getAbsolutePath();

            lblanh.setIcon(ResizeImage(String.valueOf(duongdananh)));
            System.out.println(duongdananh);

        } catch (Exception ex) {
            System.out.println("chưa chọn ảnh");
            System.out.println(duongdananh);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton3StateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3StateChanged

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlui;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JButton btntoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblanh;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JTable tbldanhsach;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txttim;
    private javax.swing.JTextField txttuoi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
