/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PHAN2;

import com.microsoft.sqlserver.jdbc.SQLServerDriver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NAM PC
 */
public class Bai2 extends javax.swing.JDialog {
    
    ArrayList<Students> list = new ArrayList<>();
    DefaultTableModel tableModel;
    DefaultComboBoxModel comboBoxModel;
    int index = -1;

    /**
     * Creates new form Bai2
     */
    public Bai2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        tbl.setDefaultEditor(Object.class, null);
        initCombobox();
        loadDataToArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtparentname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbostand = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbofees = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnprev = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtregid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Standard"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel1.setText("Name");

        jLabel2.setText("Address");

        txa.setColumns(20);
        txa.setRows(5);
        jScrollPane2.setViewportView(txa);

        jLabel3.setText("ParentName");

        jLabel4.setText("ContactNo");

        jLabel5.setText("Standard");

        cbostand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Fees");

        cbofees.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btninsert.setText("Insert");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnprev.setText("Prev");
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnnext, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(btnnew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btninsert, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnprev, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnexit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btninsert)
                    .addComponent(btnedit)
                    .addComponent(btnupdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnext)
                    .addComponent(btnprev)
                    .addComponent(btndelete)
                    .addComponent(btnexit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Regid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbostand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbofees, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(txtcontact))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(txtparentname))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtname)
                                    .addComponent(txtregid))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtregid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtparentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbostand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbofees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:       
        clearf();
        btninsert.setEnabled(true);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        if (checkNull() && checkregid() && check_sdt()) {
            insertf();
        }
    }//GEN-LAST:event_btninsertActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        editf();
    }//GEN-LAST:event_btneditActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        updatef();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        nextf();
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnprevActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(this, "Do You Want Delete ?", "DELETE", JOptionPane.YES_NO_OPTION);
        if (choose == JOptionPane.YES_OPTION) {
            deletef();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        exitf();
    }//GEN-LAST:event_btnexitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        disEnablef();
    }//GEN-LAST:event_formWindowOpened

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        disEnablef();
        index = tbl.getSelectedRow();
        fillToForm(index);
    }//GEN-LAST:event_tblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Bai2 dialog = new Bai2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprev;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbofees;
    private javax.swing.JComboBox<String> cbostand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl;
    private javax.swing.JTextArea txa;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtparentname;
    private javax.swing.JTextField txtregid;
    // End of variables declaration//GEN-END:variables

    private String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private String url = "jdbc:sqlserver://localhost; database = QLSV";
    private String user = "sa";
    private String password = "123";
    
    Connection conn = null;
    Statement stm = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void initCombobox() {
        String data_standard[] = {"trung cấp", "cao đẳng", "đại học"};
        String data_fees[] = {"10", "50", "100", "150", "200"};
        
        cbostand.setModel(new DefaultComboBoxModel(data_standard));
        cbofees.setModel(new DefaultComboBoxModel(data_fees));
    }
    
    private void clearf() {
        txtregid.setText("");
        txtname.setText("");
        txa.setText("");
        txtparentname.setText("");
        txtcontact.setText("");
        cbostand.setSelectedIndex(0);
        cbofees.setSelectedIndex(0);
        enablef();
        txtregid.requestFocus();
        index = -1;
    }
    
    public void enablef() {
        txtregid.setEditable(true);
        txtname.setEditable(true);
        txa.setEditable(true);
        txtparentname.setEditable(true);
        txtcontact.setEditable(true);
        cbostand.setEnabled(true);
        cbofees.setEnabled(true);
    }
    
    public void disEnablef() {
        txtregid.setEditable(false);
        txtname.setEditable(false);
        txa.setEditable(false);
        txtparentname.setEditable(false);
        txtcontact.setEditable(false);
        cbostand.setEnabled(false);
        cbofees.setEnabled(false);
        
        btninsert.setEnabled(false);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
    }
    
    private void insertf() {
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, password);
            String sql = "INSERT INTO student VALUES(?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtregid.getText());
            pst.setString(2, txtname.getText());
            pst.setString(3, txa.getText());
            pst.setString(4, txtparentname.getText());
            pst.setString(5, txtcontact.getText());
            pst.setString(6, (String) cbostand.getSelectedItem().toString());
            pst.setString(7, (String) cbofees.getSelectedItem().toString());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "add success");
            conn.close();
            clearf();
            disEnablef();
            loadDataToArrayList();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void editf() {
        enablef();
        txtregid.setEditable(false);
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);
    }
    
    private void updatef() {
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, password);
            String sql = "UPDATE student SET namee =?, addresss =?, parentname =?, phone =?, standards =?, fees =? \n"
                    + "where regid=?";
            pst = conn.prepareCall(sql);
            
            pst.setString(1, txtname.getText());
            pst.setString(2, txa.getText());
            pst.setString(3, txtparentname.getText());
            pst.setString(4, txtcontact.getText());
            pst.setString(5, (String) cbostand.getSelectedItem().toString());
            pst.setString(6, (String) cbofees.getSelectedItem().toString());
            pst.setString(7, txtregid.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "update success");
            conn.close();
            clearf();
            disEnablef();
            loadDataToArrayList();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void nextf() {
        index++;
        if (index >= list.size()) {
            JOptionPane.showMessageDialog(this, "đang ở cuối");
            index = list.size();
            index--;
            return;
        }
        tbl.setRowSelectionInterval(index, index);
        fillToForm(index);
        disEnablef();
    }
    
    private void prev() {
        index--;
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "đang ở đầu");
            index = 0;
            return;
        }
        tbl.setRowSelectionInterval(index, index);
        fillToForm(index);
        disEnablef();
    }
    
    private void deletef() {
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, password);
            String sql = "delete from student where regid=?";
            pst = conn.prepareCall(sql);
            pst.setString(1, txtregid.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "delete success");
            conn.close();
            clearf();
            disEnablef();
            loadDataToArrayList();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void exitf() {
        int choose = JOptionPane.showConfirmDialog(this, "Do You Want Exit", "EXIT", JOptionPane.YES_NO_OPTION);
        if (choose == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
    
    private void loadDataToArrayList() {
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, password);
            stm = conn.createStatement();
            String sql = "select * from student";
            rs = stm.executeQuery(sql);
            list.clear();
            
            while (rs.next()) {
                Students sv = new Students();
                sv.setReGid(rs.getInt(1));
                sv.setName(rs.getString(2));
                sv.setAddress(rs.getString(3));
                sv.setParentname(rs.getString(4));
                sv.setPhone(rs.getString(5));
                sv.setStandard(rs.getString(6));
                sv.setFees(rs.getString(7));
                list.add(sv);
            }
            conn.close();
            fillTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void fillTable() {
        tableModel = (DefaultTableModel) tbl.getModel();
        tableModel.setRowCount(0);
        for (Students sv : list) {
            tableModel.addRow(new Object[]{sv.getName(), sv.getStandard()});
        }
    }
    
    private void fillToForm(int index) {
        txtregid.setText(String.valueOf(list.get(index).getReGid()));
        txtname.setText(list.get(index).getName());
        txa.setText(list.get(index).getAddress());
        txtparentname.setText(list.get(index).getParentname());
        txtcontact.setText(list.get(index).getPhone());
        cbostand.setSelectedItem(list.get(index).getStandard());
        cbofees.setSelectedItem(list.get(index).getFees());
    }
    
    public boolean checkNull() {
        if (txtregid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your regid");
            return false;
        }
        if (txtname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your name");
            return false;
        }
        if (txa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your address ");
            return false;
        }
        if (txtparentname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your parentname ");
            return false;
        }
        if (txtcontact.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your contactNo ");
            return false;
        }
        return true;
    }
    private static final String P_regid = "\\d";
    
    public boolean checkregid() {
        Matcher matcher3 = Pattern.compile(P_regid).matcher(txtregid.getText());
        if (!matcher3.matches()) {
            JOptionPane.showMessageDialog(this, "Please enter number ");
            return false;
        }
        for (Students sv : list) {
            if (txtregid.getText().equalsIgnoreCase(String.valueOf(sv.getReGid()))) {
                JOptionPane.showMessageDialog(this, "Duplicate");
                return false;
            }
        }
        return true;
    }
    private static final String P_SDT = "^0\\d{9}";
    
    public boolean check_sdt() {
        Matcher matcher3 = Pattern.compile(P_SDT).matcher(txtcontact.getText());
        if (!matcher3.matches()) {
            JOptionPane.showMessageDialog(this, "ContactNo sai định dạng");
            return false;
        }
        return true;
    }
//    private static final String P_parentname = "\\[Aa-zZ]\\{10}";
//    
//    public boolean check_parentname() {
//        Matcher matcher3 = Pattern.compile(P_parentname).matcher(txtparentname.getText());
//        if (!matcher3.matches()) {
//            JOptionPane.showMessageDialog(this, "Parentname sai định dạng");
//            return false;
//        }
//        return true;
//    }
}
