/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author adm1n
 */
public class Lab6Gui extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Lab6Gui
     */
    
    Thread dongho;
    
    ThreadXoSo HangTram;
    ThreadXoSo HangChuc;
    ThreadXoSo HangDonVi;
    
    public void LoadDongHo()
    {
      dongho= new Thread()
      {
         @Override
            public void run()
            {
            while(true)
                {
                    try
                    {
                    Date d = new Date();
                    SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss aa dd/MM/YYYY");
                    String time=f.format(d);
                    lbldongho.setText(time);
                    Thread.sleep(1000);
                 
                    }
                catch(Exception ex)
                    {
                    break;
                    }
           
                }
           }
       
      };
       dongho.start();
      
     
    }
    
    public Lab6Gui() {
        initComponents();
        LoadDongHo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldongho = new javax.swing.JLabel();
        txthangtram = new javax.swing.JTextField();
        txthangchuc = new javax.swing.JTextField();
        txthangdonvi = new javax.swing.JTextField();
        btnhangtram = new javax.swing.JButton();
        btnchuc = new javax.swing.JButton();
        btndonvi = new javax.swing.JButton();
        btnstop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbldongho.setText("jLabel1");

        btnhangtram.setText("Start");
        btnhangtram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangtramActionPerformed(evt);
            }
        });

        btnchuc.setText("Start");
        btnchuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchucActionPerformed(evt);
            }
        });

        btndonvi.setText("Start");
        btndonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonviActionPerformed(evt);
            }
        });

        btnstop.setText("Stop");
        btnstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnhangtram)
                            .addComponent(txthangtram, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txthangchuc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txthangdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnchuc)
                                .addGap(47, 47, 47)
                                .addComponent(btndonvi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnstop)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbldongho)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthangtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangchuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhangtram)
                    .addComponent(btnchuc)
                    .addComponent(btndonvi))
                .addGap(27, 27, 27)
                .addComponent(btnstop)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhangtramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangtramActionPerformed
        // TODO add your handling code here:
        HangTram = new ThreadXoSo(txthangtram);
        HangTram.start();
        btnhangtram.setEnabled(false);
    }//GEN-LAST:event_btnhangtramActionPerformed

    private void btnstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstopActionPerformed
        // TODO add your handling code here:
        HangTram.stop();
        btnhangtram.setEnabled(true);
        
        HangChuc.stop();
        btnchuc.setEnabled(true);
    
        HangDonVi.stop();
        btndonvi.setEnabled(true);
    }//GEN-LAST:event_btnstopActionPerformed

    private void btnchucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchucActionPerformed
        // TODO add your handling code here:
        HangChuc = new ThreadXoSo(txthangchuc);
        HangChuc.start();
        btnchuc.setEnabled(false);
    }//GEN-LAST:event_btnchucActionPerformed

    private void btndonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonviActionPerformed
        // TODO add your handling code here:
        HangDonVi= new ThreadXoSo(txthangdonvi);
        HangDonVi.start();
        btndonvi.setEnabled(false);
        
    }//GEN-LAST:event_btndonviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchuc;
    private javax.swing.JButton btndonvi;
    private javax.swing.JButton btnhangtram;
    private javax.swing.JButton btnstop;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JTextField txthangchuc;
    private javax.swing.JTextField txthangdonvi;
    private javax.swing.JTextField txthangtram;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
