/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.lab42;

import javax.swing.JOptionPane;

/**
 *
 * @author adm1n
 */
public class Lab4Bai1 extends javax.swing.JFrame {

    /**
     * Creates new form Lab4Bai1
     */
    public Lab4Bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JPasswordField();
        txtnhaplaimatkhau = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtluong = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btndangky = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NHAP TEN");

        jLabel2.setText("NHAP MAT KHAU");

        txtmatkhau.setText("jPasswordField1");
        txtmatkhau.setToolTipText("Mat khau khong rong va >=5 ký tự");

        txtnhaplaimatkhau.setText("jPasswordField2");

        jLabel3.setText("NHAP LAI MAT KHAU");

        jLabel4.setText("NHAP NGAY SINH");

        txtngaysinh.setToolTipText("nhập dd/mm/yyyy");

        jLabel5.setText("NHAP LUONG");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel6.setText("NHAP EMAIL");

        jLabel7.setText("DANG KY");

        btndangky.setText("DANG KY");
        btndangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnhaplaimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtten)
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaysinh)
                            .addComponent(txtluong)
                            .addComponent(txtemail)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btndangky, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnhaplaimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btndangky)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btndangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkyActionPerformed
        // TODO add your handling code here:
     String thongbao="";
     if(txtten.getText().equals(""))
         thongbao+="Phải Nhập Họ Tên \n";
     
     if(txtmatkhau.getText().equals("")|| txtmatkhau.getText().length()<5)
         thongbao+="Mật Khẩu Không Hợp Lệ \n";
     
     try
     {
        if(txtmatkhau.getText().equals(txtnhaplaimatkhau.getText())==false)
        {
         throw new Exception();
        }
     }
     catch(Exception ex)
     {
         thongbao+="Hai mật khẩu không khớp\n";
     }
     
     try
     {
     double luong= Double.parseDouble(txtluong.getText());
     if(luong<0)
         throw new Exception();
     }
     catch(Exception ex)
     {
         thongbao+="Lương nhập phải là số, phải >0 \n";
     }
     
      //kiemtra ngay sinh
      try
      {
      TestDate.parse(txtngaysinh.getText(), "dd-mm-yyyy");
      }
      catch(Exception ex)
      {
          thongbao+="Ngày sinh nhập cho đúng kiểu dd-mm-yyyy \n";
      }
      
      //kiem tra email
     try
     {
      TestMail1.parseEmail(txtemail.getText());
     }
     catch(Exception ex)
     {
         thongbao+="Email Không Hợp lệ";
     }
      
     if(thongbao!="")
     {
         JOptionPane.showMessageDialog(this, thongbao);
     }
     else
     {JOptionPane.showMessageDialog(this, "Ok tất cả dữ liệu đều nhập đúng cho phép làm");
     
     }
     
     
     
        
        
        
        
        
        /*  String thongbao="";
       
      if(txtten.getText().equals(""))
      {
          thongbao+="Phai Nhap Ho Ten \n";
            
          
      }
      if(txtmatkhau.getText().equals("") || txtmatkhau.getText().length()<5)
          thongbao+="Mật Khẩu Không Hợp Lê \n";
      
      
     try
     {
      if(txtmatkhau.getText().equals(txtnhaplaimatkhau.getText())==false)
      {
          throw new Exception();
      }
     }
     catch(Exception ex)
     {
         thongbao+="2 mật khẩu không giống nhau \n";
     }
     
     try
     {
     double luong=Double.parseDouble(txtluong.getText());
     if (luong<=0)
         throw new Exception();
     }
     catch(Exception ex)
     {
         thongbao+="Luong phai là số và >0 \n";
     }
     
     // test email
     try
     {
     TestMail.parseEmail(txtemail.getText());
     }
     catch(Exception ex)
     {
         thongbao+="email không hợp lệ \n";
     }
     
      try
      {
          TestDate.parse(txtngaysinh.getText(), "dd-mm-yyyy");
      }
      catch(Exception ex)
      {
          thongbao+="ngày Sinh không hợp lê dd-mm-yyyy";
      }
     
     
     
     
     if(thongbao=="")
     {  JOptionPane.showMessageDialog(this,"ok rồi");
          
     }
     else
         JOptionPane.showMessageDialog(this,thongbao); 
     
     
        */
     
    }//GEN-LAST:event_btndangkyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab4Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab4Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab4Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab4Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab4Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangky;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtluong;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JPasswordField txtnhaplaimatkhau;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
