/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.lab6threadlop3;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author adm1n
 */
public class XoSoPoLyGui extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form XoSoPoLyGui
     */
    
    Thread dongho;
    Thread hangchucnghin;
    Thread hangdonvi;
    Thread hangchuc;
    Thread hangtram;
    Thread hangnghin;
    public void LoadDongHo()
    {
    
        dongho=new Thread()
      {
       @Override
       public void run()
        {
         while(true)
         {
             Date d = new Date();
             
             SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss aa dd/MM/YYYY");
             String time=f.format(d);
             lbldongho.setText(time + "");
            try
            {
             Thread.sleep(1000);
            }
            catch(Exception ex)
            {
                break;
            }
         }
        }
            
      };
        dongho.start();
        
    }
    
    public XoSoPoLyGui() {
        initComponents();
        LoadDongHo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldongho = new javax.swing.JLabel();
        txthangchucnghin = new javax.swing.JTextField();
        txthangnghin = new javax.swing.JTextField();
        txthangtram = new javax.swing.JTextField();
        btnhangchucnghin = new javax.swing.JButton();
        btnhangnghin = new javax.swing.JButton();
        btnhangtram = new javax.swing.JButton();
        txthangchuc = new javax.swing.JTextField();
        btnhangchuc = new javax.swing.JButton();
        btnhangdonvi = new javax.swing.JButton();
        txthangdonvi = new javax.swing.JTextField();
        btnstop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbldongho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbldongho.setText("jLabel1");

        txthangchucnghin.setText("jTextField1");

        txthangnghin.setText("jTextField2");

        txthangtram.setText("jTextField3");

        btnhangchucnghin.setText("Start");
        btnhangchucnghin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangchucnghinActionPerformed(evt);
            }
        });

        btnhangnghin.setText("Start");
        btnhangnghin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangnghinActionPerformed(evt);
            }
        });

        btnhangtram.setText("Start");
        btnhangtram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangtramActionPerformed(evt);
            }
        });

        txthangchuc.setText("jTextField1");

        btnhangchuc.setText("Start");
        btnhangchuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangchucActionPerformed(evt);
            }
        });

        btnhangdonvi.setText("Start");
        btnhangdonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangdonviActionPerformed(evt);
            }
        });

        txthangdonvi.setText("jTextField2");

        btnstop.setText("Stop");
        btnstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstopActionPerformed(evt);
            }
        });

        jLabel1.setText("XO SO ĐỒNG NAI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnstop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnhangchucnghin)
                                    .addComponent(txthangchucnghin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthangnghin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnhangnghin))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthangtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnhangtram))))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhangchuc)
                            .addComponent(txthangchuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnhangdonvi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txthangdonvi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthangchucnghin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangnghin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangchuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthangdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhangchucnghin)
                    .addComponent(btnhangnghin)
                    .addComponent(btnhangtram)
                    .addComponent(btnhangchuc)
                    .addComponent(btnhangdonvi))
                .addGap(44, 44, 44)
                .addComponent(btnstop)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhangchucnghinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangchucnghinActionPerformed
        // TODO add your handling code here:
       hangchucnghin = new ThreadXoSoPoLy2021(txthangchucnghin);
       hangchucnghin.start();
       btnhangchucnghin.setEnabled(false);
               
    }//GEN-LAST:event_btnhangchucnghinActionPerformed

    private void btnstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstopActionPerformed
        // TODO add your handling code here:
       
       
         hangdonvi.stop();
        btnhangdonvi.setEnabled(true);
         
        hangchuc.stop();
        btnhangchuc.setEnabled(true);
        
         hangtram.stop();
        btnhangtram.setEnabled(true);
        
       hangnghin.stop();
       btnhangnghin.setEnabled(true);
        
       hangchucnghin.stop();
        btnhangchucnghin.setEnabled(true); 
        
        
        
    }//GEN-LAST:event_btnstopActionPerformed

    private void btnhangnghinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangnghinActionPerformed
        // TODO add your handling code here:
         hangnghin = new ThreadXoSoPoLy2021(txthangnghin);
       hangnghin.start();
       btnhangnghin.setEnabled(false);
    }//GEN-LAST:event_btnhangnghinActionPerformed

    private void btnhangtramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangtramActionPerformed
        // TODO add your handling code here:
         hangtram = new ThreadXoSoPoLy2021(txthangtram);
       hangtram.start();
       btnhangtram.setEnabled(false);
    }//GEN-LAST:event_btnhangtramActionPerformed

    private void btnhangchucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangchucActionPerformed
        // TODO add your handling code here:
         hangchuc = new ThreadXoSoPoLy2021(txthangchuc);
       hangchuc.start();
       btnhangchuc.setEnabled(false);
    }//GEN-LAST:event_btnhangchucActionPerformed

    private void btnhangdonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangdonviActionPerformed
        // TODO add your handling code here:
         hangdonvi = new ThreadXoSoPoLy2021(txthangdonvi);
       hangdonvi.start();
       btnhangdonvi.setEnabled(false);
    }//GEN-LAST:event_btnhangdonviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XoSoPoLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XoSoPoLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XoSoPoLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XoSoPoLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XoSoPoLyGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhangchuc;
    private javax.swing.JButton btnhangchucnghin;
    private javax.swing.JButton btnhangdonvi;
    private javax.swing.JButton btnhangnghin;
    private javax.swing.JButton btnhangtram;
    private javax.swing.JButton btnstop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JTextField txthangchuc;
    private javax.swing.JTextField txthangchucnghin;
    private javax.swing.JTextField txthangdonvi;
    private javax.swing.JTextField txthangnghin;
    private javax.swing.JTextField txthangtram;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
